### PR TITLE
Edit Profile use case

### PR DESCRIPTION
**Pull request by elidle**
Initial Implementation of Edit Profile, which allows changes to the instance attributes of entities implementing `User`.

- Implemented both interfaces adapters (Controller, Presenter) 
- Implemented all use cases (Data access interface, Input boundary, Input data, Interactor, Output boundary, Output data)
- Made changes to `User ` entity
- Created` test/use_case/EditProfileTest.java`, to be implemented later

### CODE REVIEW

**Comment by faraazzz31** [comment]
The implementation looks good so far!

**Review by faraazzz31 — APPROVED** [review]
The implementation looks good so far!

**Review by ChristofferTan — APPROVED** [review]
Good work, Razan!

**Comment by ChristofferTan** [comment]
Hi, for the InMemoryUserDataAccessObject, I have updated the file for the AddFriend use case. can you add those changes to your branch

**Comment by ChristofferTan** [comment]
I have resolved the conflicts, can you try to look at it?

**Review by JanisJ22 — CHANGES_REQUESTED** [review]
Great job overall! I made some minor changes to resolve conflicts with my branch's use case.

Just to make sure, did you implement this use case's factory to create `EditProfileView` and connect `EditProfilePresenter`, `EditProfileDataAccessInterface`, and `EditProfileInteractor` to `EditProfileController`? We might need it later.

**Review by elidle — COMMENTED** [review]
Thanks for the suggestion. I agree with the changes. I think there are no problem with it.

**Review by faraazzz31 — APPROVED** [review]
The conflicts seem resolved. Great work!

**Pull request merged**
